/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicDataRouteImport } from './routes/public-data'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'

const PublicDataRoute = PublicDataRouteImport.update({
  id: '/public-data',
  path: '/public-data',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/public-data': typeof PublicDataRoute
  '/about': typeof AboutIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/public-data': typeof PublicDataRoute
  '/about': typeof AboutIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/public-data': typeof PublicDataRoute
  '/about/': typeof AboutIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/get-started' | '/public-data' | '/about' | '/contact-us'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/get-started' | '/public-data' | '/about' | '/contact-us'
  id:
    | '__root__'
    | '/'
    | '/get-started'
    | '/public-data'
    | '/about/'
    | '/contact-us/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetStartedRoute: typeof GetStartedRoute
  PublicDataRoute: typeof PublicDataRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public-data': {
      id: '/public-data'
      path: '/public-data'
      fullPath: '/public-data'
      preLoaderRoute: typeof PublicDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetStartedRoute: GetStartedRoute,
  PublicDataRoute: PublicDataRoute,
  AboutIndexRoute: AboutIndexRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
